### ISSUE TITLE
Elasticsearch Hook: Configuration of index suffix date pattern

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/secureCodeBox-v2#105]
As a SCB User i would like to configure the elasticsearch index pattern more precisely when i install the elasticsearch persistence hook. This feature will be useful to optimize the elasticsearch result index size, rollover strategie and performance.

As for now it is already possible to configure the *index prefix* via the helm chart config:
```yaml
# Define a specific index prefix
indexPrefix: "scbv2" 
```

Additionally it should be possible to configure a date pattern as *suffix* to change the index aggregation level:

```yaml
# Define a specific index prefix
indexPrefix: "scbv2"
# Define a specific index suffix based on date pattern (YEAR, MONTH, WEEK, DATE)
indexSuffix: “YEAR-MONTH-DATE”
# Define if the name of the namespace where this hook is deployed to must be added to the index name. The namespace can be used to separate index by tenants (namespaces).
indexAppendNamespace: true
```

### Examples
Example index names that should be possible to configure:

- `scbv2-team-2020-10-05` (daily rollover pattern, append namespace: true)
- `scbv2-team-2020-10` (monthly rollover pattern, append namespace: true)
- `scbv2-team-2020` (yearly rollover pattern, append namespace: true)
- `scbv2-team-2020-45` (weekly rollover pattern, append namespace: true)
- `scbv2-team` (no rollover pattern, append namespace: true)

- `scbv2-2020-10-05` (daily rollover pattern, append namespace: false)
- `scbv2-2020-10` (monthly rollover pattern, append namespace: false)
- `scbv2-2020` (yearly rollover pattern, append namespace: false)
- `scbv2-2020-45` (weekly rollover pattern, append namespace: false)
- `scbv2` (no rollover pattern, append namespace: false)

### Where to start?
As a starting point here a pointer to the current implementation:

https://github.com/secureCodeBox/secureCodeBox-v2/blob/25b548d47795dba2891f45c7d11381ab69275ac5/hooks/persistence-elastic/hook.js#L50

### Todos:
- [ ]  Update HelmChart config defaults
- [ ]  Implement feature within hook.js
- [ ]  Add additional unit tests for the different configuration options/combinations.

**Comment by J12934** [comment]
Would recommend to use a more standard time string format for the `indexSuffix`config option.

E.g. the format used by moment.js or [dayjs](https://www.npmjs.com/package/dayjs), e.g. `YYYY-MM-DD`

**Comment by rseedorff** [comment]
Great catch 👍🏻 you are absolutely right. I will update the description accordingly

**Comment by sufisaid** [comment]
Hello. I could take this one if that's ok with you?

**Comment by rseedorff** [comment]
Hi @sufisaid,
that would be great 👍🏻 we appreciate any help and currently nobody is actively working on this issue.
